<?php
echo $this->headLink()
        ->prependStylesheet($this->basePath() . '/js/codebase/dhtmlxscheduler.css');
echo $this->headScript()
        ->prependFile($this->basePath() . '/js/jqueryui-multisearch.js')
        ->prependFile($this->basePath() . '/js/codebase/locale/locale_pt.js')
        ->prependFile($this->basePath() . '/js/codebase/ext/dhtmlxscheduler_recurring.js')
        ->prependFile($this->basePath() . '/js/codebase/ext/dhtmlxscheduler_tooltip.js')
        ->prependFile($this->basePath() . '/js/codebase/dhtmlxscheduler.js')
        ->prependFile($this->basePath() . '/js/lodash.underscore.min.js')
        ->prependFile($this->basePath() . '/js/jquery-ui.js');
?>

<style>
textarea {
   resize: none;
   font-size: 12px !important;
}

input[data-role="input"] {
   outline: none;
   border: none;
   font-size: 12px;
   color: #555;
   vertical-align: middle;
   padding: 3px 4px;
   margin: 3px;
}

input.error {
   color: #f00;
}

[data-role="picker"] {
   z-index: 1080;
}

a:focus {
   outline: none;
}

a.list-group-item.hover {
    background-color: #F5F5F5;
    text-decoration: none;
}

a.label-default {
   cursor: pointer;
   font-size: 12px;
   margin: 3px;
   color: #555;
   background-color: #F7F7F7;
   text-decoration: none;
}

a.label-default.hover {
   background-color: #DFDFDF;
   text-decoration: none;
}

a.label-default.active {
   text-decoration: none;
}

.panel {
   margin: 0;
   transition: border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s;
}

.panel.focus {
   border-color: #66AFE9;
   box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset, 0 0 8px rgba(102, 175, 233, 0.6);
   outline: 0 none;
}

.panel-body {
    padding: 3px 6px;
}

.popover {
   max-width: 347px;
   min-width: 276px;
}

.popover-content {
   overflow: hidden;
   font-size: 90%;
}

.popover-content .col-lg-4, .popover-content .col-lg-8 {
   padding: 0 5px
}
</style>

<script id="multisearch" type="text/template">
   <div>
      <div class="panel panel-default">
         <div data-role="selected-list" class="panel-body">
            <input class="pull-left" data-role="input" type="text" placeholder=""/>
         </div>
      </div>
      <div data-role="picker" class="panel panel-default">
         <div class="list-group" data-role="picker-list">
         </div>
      </div>
   </div>
</script>

<script id="contact-item" type="text/template">
   <a class="list-group-item" href="#">
      <small><%= display_name %> (<%= primary_email %>)</small>
   </a>
</script>

<script id="selected-item" type="text/template">
   <a class="label label-default pull-left"><%= display_name %>&nbsp;<span class="glyphicon glyphicon-remove" data-action="remove" aria-hidden="true"></span></a>
</script>

<script id="contact-info" type="text/template">
   <div class="popover bottom fade">
     <div class="arrow"></div>
     <h3 class="popover-title"><%= display_name %></h3>
     <div class="popover-content">

         <div class="row">
           <div class="col-lg-4 text-right"><strong>Company</strong></div>
           <div class="col-lg-8"><%= organization %></div>
         </div>

         <div class="row">
           <div class="col-lg-4 text-right"><strong>Email</strong></div>
           <div class="col-lg-8"><%= primary_email %></div>
         </div>

         <div class="row">
           <div class="col-lg-4 text-right"><strong>Phone</strong></div>
           <div class="col-lg-8"><%= primary_phone %></div>
         </div>

     </div>
   </div>
</script>

<script>

function showComplete() {

}

localData = [
         {"display_name": "Neal, Amelia R.","organization":"XYZ Company","primary_email":"pede@nibh.com","primary_phone":"(577) 324-9152"},
         {"display_name": "Cervantes, Colton Z.","organization":"XYZ Company","primary_email":"imperdiet.dictum.magna@SuspendissesagittisNullam.com","primary_phone":"(730) 491-0518"},
         {"display_name": "Thornton, Marvin H.","organization":"XYZ Company","primary_email":"tristique@in.ca","primary_phone":"(530) 962-1617"},
         {"display_name": "Watkins, Leilani C.","organization":"XYZ Company","primary_email":"amet.massa@a.edu","primary_phone":"(368) 554-4860"},
         {"display_name": "Blake, Sawyer Z.","organization":"XYZ Company","primary_email":"sodales@Pellentesquetincidunttempus.edu","primary_phone":"(247) 412-3266"},
         {"display_name": "Fuller, Jennifer W.","organization":"XYZ Company","primary_email":"ullamcorper.Duis.at@ullamcorpernislarcu.org","primary_phone":"(263) 771-8743"},
         {"display_name": "Pollard, Noel K.","organization":"XYZ Company","primary_email":"sagittis.Duis.gravida@Proin.com","primary_phone":"(466) 130-3283"},
         {"display_name": "Clemons, Thomas Y.","organization":"XYZ Company","primary_email":"Integer@sem.org","primary_phone":"(463) 990-6407"},
         {"display_name": "Gilbert, Kimberley D.","organization":"XYZ Company","primary_email":"magna.Cras.convallis@metuseuerat.com","primary_phone":"(845) 785-9757"},
         {"display_name": "Green, Zeus L.","organization":"XYZ Company","primary_email":"Ut.tincidunt@pedeCumsociis.edu","primary_phone":"(894) 870-2892"},
         {"display_name": "Alston, Lesley P.","organization":"XYZ Company","primary_email":"lectus.quis@gravida.edu","primary_phone":"(709) 389-5236"},
         {"display_name": "Perry, Arthur R.","organization":"XYZ Company","primary_email":"orci.lacus.vestibulum@elit.com","primary_phone":"(202) 128-1825"},
         {"display_name": "Holman, Anastasia T.","organization":"XYZ Company","primary_email":"lorem.vehicula.et@sitametconsectetuer.com","primary_phone":"(756) 127-8864"},
         {"display_name": "Howe, Zena W.","organization":"XYZ Company","primary_email":"nisi@Nulla.org","primary_phone":"(925) 386-6531"},
         {"display_name": "Gray, Evan N.","organization":"XYZ Company","primary_email":"nonummy.ac.feugiat@mollis.edu","primary_phone":"(880) 530-9214"},
         {"display_name": "Gates, Galvin D.","organization":"XYZ Company","primary_email":"eu@nislQuisquefringilla.com","primary_phone":"(410) 733-0830"},
         {"display_name": "Hendrix, Anne E.","organization":"XYZ Company","primary_email":"ornare.libero.at@tempor.org","primary_phone":"(348) 482-7943"},
         {"display_name": "Avery, Nerea V.","organization":"XYZ Company","primary_email":"Sed@sedconsequatauctor.org","primary_phone":"(284) 585-9041"},
         {"display_name": "Tillman, Debra V.","organization":"XYZ Company","primary_email":"Nunc.lectus@justonecante.edu","primary_phone":"(961) 408-4886"},
         {"display_name": "Meadows, Mona F.","organization":"XYZ Company","primary_email":"vestibulum.neque.sed@etlaciniavitae.com","primary_phone":"(322) 745-5208"},
         {"display_name": "Yates, Zena A.","organization":"XYZ Company","primary_email":"orci.lacus.vestibulum@Quisque.org","primary_phone":"(975) 832-4608"},
         {"display_name": "Hodges, Eric E.","organization":"XYZ Company","primary_email":"natoque.penatibus@Sedneque.edu","primary_phone":"(984) 164-0737"},
         {"display_name": "Mclaughlin, Tana K.","organization":"XYZ Company","primary_email":"pharetra.Quisque.ac@Intinciduntcongue.org","primary_phone":"(213) 306-7213"},
         {"display_name": "Rosario, Upton A.","organization":"Outside Path Partners","primary_email":"magna.et@Sedpharetrafelis.edu","primary_phone":"(407) 281-1295"}
     ];

// Need an id ... auto-generate it
for (var i=1;i<localData.length;i++)
   localData[i].id = i;

</script>

<style type="text/css" media="screen">
    html, body{
        margin:0px;
        padding:0px;
        height:100%;
        overflow:hidden;
    }	
    div#email {
   width: 650px;
border: 1px solid #CCC;
z-index: 99999999;
height:30px;
}
.panel-body {
padding: 0px;
}
</style>

<script>
    function init() {

        dhtmlXTooltip.config.className = 'dhtmlXTooltip tooltip';
        dhtmlXTooltip.config.timeout_to_display = 50;
        dhtmlXTooltip.config.delta_x = 15;
        dhtmlXTooltip.config.delta_y = -20;

        scheduler.config.multi_day = true;
        scheduler.config.xml_date = "%Y-%m-%d %H:%i";
        scheduler.config.details_on_dblclick = true;
        scheduler.config.details_on_create = true;

        scheduler.config.event_duration = 35;
        scheduler.config.occurrence_timestamp_in_utc = true;
        scheduler.config.include_end_by = true;
        scheduler.config.repeat_precise = true;
        scheduler.form_blocks["contact_view"]={
                render:function(sns){
                        var html = '<div class="dhx_cal_ltext" style="height: 31px;">';
                        html += '<div data-control="multisearch" size="32" id="email" onclick="auto_complete();"></div></div>';
                        return html;
                },
                set_value:function(node,value,ev){
                        node.childNodes[0].value=value||"";
                        // we must loop through all nodes because we use the autocomplete plugin which sometimes adds
                        // additional html elements therefore changing the position of the inputs
                        $.each(node.childNodes, function(index, item) { 
                            if ($(item).attr("id") == "email") {
                                node.childNodes[index].value=ev.email||"";
                            }
                        });
                },
                get_value:function(node,ev){
                        // we must loop through all nodes because we use the autocomplete plugin which sometimes adds
                        // additional html elements therefore changing the position of the inputs
                        $.each(node.childNodes, function(index, item) { 
                            if ($(item).attr("id") == "email") {
                                ev.email = node.childNodes[index].value;
                            }
                        });
                        return node.childNodes[0].value;
                },
                // focus:function(node){
                //         var a=node.childNodes[0]; a.select(); a.focus(); 
                // }
        }
        
        scheduler.config.lightbox.sections = [
            {name: "Título", height: 50, map_to: "text", type: "textarea", focus: true},
            {name: "description", height: 50, map_to: "details", type: "textarea", focus: true},
            {name: "Convidados", height: 50, map_to: "convidados", type: "textarea", focus: true},
            {name: "Email", height: 50, map_to: "email", type: "contact_view", focus: true},
            {name: "Endereço", height: 43, map_to: "event_location", type: "textarea", default_value: "Rua São José, nº 01, Centro - Fortaleza-CE"},
            //{name: "recorrente", type: "recurring", map_to: "rec_type", button: "recurring"}, //Agendamento Recorrente... implantar posteriormente
            {name: "time", height: 72, type: "time", map_to: "auto"}
        ];

        scheduler.config.full_day = true; // enable parameter to get full day event option on the lightbox form
        scheduler.config.buttons_left = ["dhx_save_btn", "dhx_cancel_btn"];
        //scheduler.config.buttons_left = ["dhx_save_btn", "dhx_cancel_btn", "locate_button"];
        //scheduler.locale.labels["locate_button"] = "Localização"; //Implantar posteriormente

        scheduler.init('scheduler_here', new Date(<?php echo date("Y"); ?>, <?php echo date("m") - 1; ?>, <?php echo date("d"); ?>), "day");
        scheduler.load("<?php echo $this->url('agenda', array('action' => 'list-agenda')); ?>", "json");
        var dp = new dataProcessor("<?php echo $this->url('agenda', array('action' => 'addedit-agenda')); ?>");
        dp.init(scheduler);
       
          scheduler.attachEvent("onBeforeLightbox", function(e) {
            console.log('asdasdasd');
            return true;
          });
        scheduler.attachEvent("onLightboxButton", function(button_id, node, e) {
            if (button_id == "locate_button") {
                alert("Funções da ação de Localização/Mapa");
            }
         
            var lightbox_form = scheduler.getLightbox(); // this will generate lightbox form

            var inputs = lightbox_form.getElementsByTagName('input');
            var date_of_end = null;
            for (var i = 0; i < inputs.length; i++) {

                if (inputs[i].name == "date_of_end") {
                    date_of_end = inputs[i];
                    break;
                }
            }

            var repeat_end_date_format = scheduler.date.date_to_str(scheduler.config.repeat_date);
            var show_minical = function() {
                if (scheduler.isCalendarVisible())
                    scheduler.destroyCalendar();
                else {
                    scheduler.renderCalendar({
                        position: date_of_end,
                        date: scheduler.getState().date,
                        navigation: true,
                        handler: function(date, calendar) {
                            date_of_end.value = repeat_end_date_format(date);
                            scheduler.destroyCalendar()
                        }
                    });
                }
            };
            date_of_end.onclick = show_minical;
        });

 
        scheduler.templates.event_text = function(start, end, ev) {
            return "<b>" + ev.text + "</b><br>" + ev.details + "<br><i>" + ev.event_location + "</i>";
        };

        var format = scheduler.date.date_to_str("%d/%m/%Y %H:%i");
        scheduler.templates.tooltip_text = function(start, end, event) {
            return "<b>Título:</b> " + event.text + "<br/>\n\
                            <b>Descrição:</b> " + event.details + "<br/>\n\
                            <b>Participantes:</b> " + event.convidados + "<br/>\n\
                            <b>Local:</b> " + event.event_location + "<br/>\n\
                            <b>Inicia em:</b> " + format(start) + "<br/>\n\
                            <b>Termina em:</b> " + format(end);
        };

        showComplete();
    }
  function auto_complete(){
    console.log('auto_complete')

  $('.dhx_cal_larea > .dhx_cal_ltext textarea').click(function(){
    alert('asasdjkasdhjasd asdop');
  })
  $('.dhx_scale_holder_now').click(function(){
   $('.dhx_cal_larea > .dhx_cal_ltext').attr('data-control', 'multisearch');
  });


   var multiSearch = _.template( $('#multisearch').html() ),
       infoBox = _.template( $('#contact-info').html() );

   // Since you can tab through fields, redirect the focus
   // event to click just in case.
   $( document.body ).on( 'focusin', 'input, textarea', function( event ) {
      $( event.target ).trigger( 'click' );
 console.log('focusin')
   });

   


    $('#email').append( multiSearch() )
      .children()

      .on( 'click', function simulateFocus( event ) {
 console.log('click')
            /*
            *  Simulate the nice input focus effect for
            *  Bootstrap form-controls.  Since there's one
            *  on the page, it looks wierd if these boxes
            *  don't match.
            */

            var $me = $( this ),
                $panel = $me.find( '.panel' );

            if ( !$panel.is( '.focus' ) ) {

               $panel.addClass( 'focus' );

               _.defer( function() {
                  $( document.body ).on( 'click.focus', function( e ) {
                     if ( $me.has( e.target ).length === 0 ) {
                        $panel.removeClass( 'focus' );
                        $( document.body ).off( 'click.focus' );
                     }
                  });
               });
            }

         })

      .multisearch( {

         source: localData,

         keyAttrs: [ 'id' ],
         searchAttrs: [ 'display_name', 'primary_email' ],

         formatPickerItem: _.template( $('#contact-item').html() ),
         formatSelectedItem: _.template( $('#selected-item').html() ),

         buildNewItem: function( text ) {
            return { id: null, display_name: text, organization: '', primary_phone: '', primary_email: text };
         },

         adding: function( event, ui ) {
            var validater = new RegExp('^(?:[^,]+@[^,/]+\.[^,/]+|)$');

            $( this ).find( 'input' ).removeClass( 'error' );
            if ( ui.notfound ) {
               if ( !validater.test( ui.data.primary_email ) ) {
                  $( this ).find( 'input' ).addClass( 'error' );
                  return false;
               }
            }
         },

         itemselect: function( event, ui ) {

            // Generate from template and add to DOM
            var $info = $( infoBox( ui.data ) ).insertAfter( $( this ) ).show();

            // Use jQueryUI Position utility to move it to the right spot
            $info.position({
               my: 'center top+10',
               at: 'center bottom',
               of: ui.element
            });

            // Trigger the Bootstrap fade transition
            $info.addClass( 'in' );

            // Several things are happening here:
            //  1) This click event is still bubbling, listen to
            //     click now, and it will be caught before the popover
            //     ever appears.  Deferring it pushes the execution outside
            //     of the current call stack
            //  2) Clicks inside the popover are fine.  Use the $.has() function
            //     to see if any part of the target is or is inside the popover
            //     element.  Only remove if that is not true.  Remember, has()
            //     returns a set of elements unlike is() which returns true/false.
            //  3) It makes sense to animate the box out.  Leave some time for that
            //     to happen before toasting the element from the DOM.
            _.defer( function() {
               $( document ).on( 'click.info', function( e ) {
                  if ( $info.has( e.target ).length === 0 ) {
                     $info.removeClass( 'in' );
                     _.delay( function() { $info.remove(); }, 500 );
                     $( document ).off( 'click.info' );
                  }
               });
            });
         },
      });
  }
</script>
<div id="scheduler_here" class="dhx_cal_container container" style='width:100%; height:85%;'>
    <div class="dhx_cal_navline">
        <div class="dhx_cal_prev_button">&nbsp;</div>
        <div class="dhx_cal_next_button">&nbsp;</div>
        <div class="dhx_cal_today_button"></div>
        <div class="dhx_cal_date"></div>
        <div class="dhx_cal_tab" name="day_tab" style="right:204px;"></div>
        <div class="dhx_cal_tab" name="week_tab" style="right:140px;"></div>
        <div class="dhx_cal_tab" name="month_tab" style="right:76px;"></div>
    </div>
    <div class="dhx_cal_header">
    </div>
    <div class="dhx_cal_data">
    </div>
</div>