<div class="container-fluid">
    <?php
    $this->headScript()->prependFile($this->basePath() . '/js/ui-bootstrap-tpls-0.10.0.min.js');
    $this->headScript()->prependFile($this->basePath() . '/js/angular.min.js');
    ?>
    <script>
        var app = angular.module('myApp', ['ui.bootstrap']);
        app.filter('startFrom', function() {
            return function(input, start) {
                if (input) {
                    start = +start; //parse to int
                    return input.slice(start);
                }
                return [];
            }
        });
        app.controller('customersCrtl', function($scope, $http, $timeout) {
            $http.get('<?php echo $this->url('contatos', array('action' => 'listacontatos')); ?>').success(function(data) {
                $scope.list = data;
                $scope.currentPage = 1; //current page
                $scope.entryLimit = 10; //max no of items to display in a page
                $scope.filteredItems = $scope.list.length; //Initially for no filter  
                $scope.totalItems = $scope.list.length;
            });
            $scope.setPage = function(pageNo) {
                $scope.currentPage = pageNo;
            };
            $scope.filter = function() {
                $timeout(function() {
                    $scope.filteredItems = $scope.filtered.length;
                }, 10);
            };
            $scope.sort_by = function(predicate) {
                $scope.predicate = predicate;
                $scope.reverse = !$scope.reverse;
            };
        });
    </script>

    <?php if (isset($_SESSION['User']['userId'])) { ?>
        <nav>
            <div class="navbar-header pull-right">
                <a id="nav-expander" class="nav-expander fixed">
                    <span class="glyphicon" data-icon="&#xe0a5;"></span>
                </a>
            </div>
            <ul class="list-unstyled main-menu">
                <?php foreach ($this->users as $res) { ?>
                    <li class="clearfix"><span class="pull-left"><?php echo $res['nome'] . " " . $res['sobrenome']; ?></span> <span class="pull-right"><input type="checkbox" name="situacao-membro" id="<?php echo $res['id']; ?>" <?php if ($res['status'] == "Active") {
                echo "checked";
            } ?> data-size="small" data-on-text="Presente" data-off-text="Ausente" data-on-color="success" data-off-color="danger" data-label-text="< >"></span></li>
        <?php } ?>
            </ul>
        </nav>
<?php } ?>

    <div class="col-md-6">
        <div id="compromissos" class="table">
            <legend><span class="glyphicon" data-icon="N"></span> Agenda</legend>
            <!-- Nav tabs -->
            <ul class="nav nav-tabs">
                <li class="active"><a href="#c-hoje" data-toggle="tab" data-placement="top" data-original-title="Hoje"><span class="glyphicon" data-icon="N"></span> Hoje</a></li>
    <!--            <li class=""><a href="#c-semana" data-toggle="tab" data-placement="top" data-original-title="Esta Semana"><span class="glyphicon" data-icon="N"></span> Esta Semana</a></li>
                <li class=""><a href="#c-mes" data-toggle="tab" data-placement="top" data-original-title="Este Mês"><span class="glyphicon" data-icon="N"></span> Este Mês</a></li>-->
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
                <div class="tab-pane fade in active" id="c-hoje">
                    <div class="table-responsive">
                        <table class="table table-striped" id="datatable">
                            <thead>
                                <tr>
                                    <th>Data/Hora</th>
                                    <th>Participantes</th>
                                    <th>Local</th>
    <!--                                <th></th>-->
                                </tr>
                            </thead>
                            <tbody>
<?php foreach ($this->agenda_dia as $res) { ?>
                                    <tr>
                                        <td><?php echo $res['start_date']; ?></td>
                                        <td><?php echo $res['convidados']; ?></td>
                                        <td><?php echo $res['event_location']; ?></td>
        <!--                                <td><a href="#" data-toggle="modal" data-target="#myModal"><span class="glyphicon" data-icon="&#xe18e;"></span> detalhes</a></td>-->
                                    </tr>
<?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="tab-pane fade in" id="c-semana">
                    <div class="table-responsive">
                        <h1>SEMANA</h1>
                    </div>
                </div> 
                <div class="tab-pane fade in" id="c-mes">
                    <div class="table-responsive">
                        <h1>MÊS</h1>
                    </div>
                </div> 
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div id="ligacoes" class="table">
            <legend><span class="glyphicon" data-icon="&#xe16c;"></span> Ligações</legend>
            <!-- Nav tabs -->
            <ul class="nav nav-tabs">
                <li class="active"><a href="#l-hoje" data-toggle="tab" data-placement="top" data-original-title="Hoje"><span class="glyphicon" data-icon="&#xe16c;"></span> Hoje</a></li>
    <!--            <li class=""><a href="#l-semana" data-toggle="tab" data-placement="top" data-original-title="Esta Semana"><span class="glyphicon" data-icon="&#xe16c;"></span> Esta Semana</a></li>
                <li class=""><a href="#l-mes" data-toggle="tab" data-placement="top" data-original-title="Este Mês"><span class="glyphicon" data-icon="&#xe16c;"></span> Este Mês</a></li>-->
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
                <div class="tab-pane fade in active" id="l-hoje">
                    <div class="table-responsive">
                        <table class="table table-striped" id="datatable">
                            <thead>
                                <tr>
                                    <th>Data/Hora</th>
                                    <th>Responsável</th>
                                    <th>Assunto</th>
    <!--                                <th></th>-->
                                </tr>
                            </thead>
                            <tbody>
<?php foreach ($this->ligacoes_dia as $res) { ?>
                                    <tr>
                                        <td><?php echo $res['data_hora']; ?></td>
                                        <td><?php echo $res['membro']; ?></td>
                                        <td><?php echo $res['assunto']; ?></td>
        <!--                                <td><a href="#" data-toggle="modal" data-target="#myModal"><span class="glyphicon" data-icon="&#xe18e;"></span> detalhes</a></td>-->
                                    </tr>
<?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="tab-pane fade in" id="l-semana">
                    <div class="table-responsive">
                        <h1>SEMANA</h1>
                    </div>
                </div> 
                <div class="tab-pane fade in" id="l-mes">
                    <div class="table-responsive">
                        <h1>MÊS</h1>
                    </div>
                </div> 
            </div>
        </div>
    </div>

    <div ng-controller="customersCrtl">
        <div class="col-md-12">
            <legend class="clearfix"><span class="glyphicon" data-icon="a"></span> Contatos <span class="pull-right" style="margin-bottom: -1px;"><input id="s-contatos" name="s-contatos" type="text" ng-model="search" ng-change="filter()" placeholder="Pesquise um dos campos" class="input-sm"></span></legend>
            <div>
                <div class="row">
                    <div class="col-md-12" ng-show="filteredItems > 0">
                        <table class="table table-striped table-bordered">
                            <thead>
                            <th>ID&nbsp;<a ng-click="sort_by('id_contato');"><i class="glyphicon glyphicon-sort"></i></a></th>
                            <th>Nome&nbsp;<a ng-click="sort_by('nome_completo');"><i class="glyphicon glyphicon-sort"></i></a></th>
                            <th>Sigla&nbsp;<a ng-click="sort_by('o_sigla');"><i class="glyphicon glyphicon-sort"></i></a></th>
                            <th>Cargo&nbsp;<a ng-click="sort_by('cargo');"><i class="glyphicon glyphicon-sort"></i></a></th>
                            <th>Telefone/Ramal&nbsp;<a ng-click="sort_by('fone');"><i class="glyphicon glyphicon-sort"></i></a></th>
                            <th>Celular&nbsp;<a ng-click="sort_by('celular');"><i class="glyphicon glyphicon-sort"></i></a></th>
                            <th>Email&nbsp;<a ng-click="sort_by('email');"><i class="glyphicon glyphicon-sort"></i></a></th>
                            </thead>
                            <tbody>
                                <tr ng-repeat="data in filtered = (list| filter:search | orderBy : predicate :reverse) | startFrom:(currentPage - 1) * entryLimit | limitTo:entryLimit">
                                    <td>{{data.id_contato}}</td>
                                    <td>{{data.nome_completo}}</td>
                                    <td>{{data.o_sigla}}</td>
                                    <td>{{data.cargo}}</td>
                                    <td>{{data.fone}} / {{data.ramal}}</td>
                                    <td>{{data.celular}}</td>
                                    <td>{{data.email}}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="col-md-12" ng-show="filteredItems == 0">
                        <div class="col-md-12">
                            <h4>Nenhum Resultado para sua Pesquisa</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>