<?php
$title = 'Excluir Ligação';
$this->headTitle($title);
$date = new \DateTime($this->escapeHtml($ligacao->l_data));
$dataAtual = $date->format('d/m/Y à\s H:i');
?>
<div class="container-fluid">
    <div class="table-responsive">
        <h1><?php echo $this->escapeHtml($title); ?></h1>

        <table class="table table-striped" id="datatable">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Membro</th>
                    <th>Destinatário</th>
                    <th>Assunto</th>
                    <th>Data</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><?php echo $this->escapeHtml($ligacao->l_id); ?></td>
                    <td><?php echo $this->escapeHtml($ligacao->l_membro); ?></td>
                    <td><?php echo $this->escapeHtml($ligacao->l_destino); ?></td>
                    <td><?php echo $this->escapeHtml($ligacao->l_assunto); ?></td>
                    <td><?php echo $dataAtual; ?></td>
                </tr>
            </tbody>
        </table>
        <div class="col-md-12 text-center">
            <h2 class="sub-header" style="margin-bottom: 20px;">Confirma Exclusão?</h2>
        </div>
        <div class="col-md-12 text-center">
            <?php $url = $this->url('ligacoes', array('action' => 'del', 'form_codigo' => $this->form_codigo)); ?>
            <form action="<?php echo $url; ?>" method="post">
                <div>
                    <input type="hidden" name="form_codigo" value="<?php echo (int) $this->form_codigo; ?>" />
                    <input type="submit" name="del" class="btn btn-primary" value="Confirmar" />
                    <input type="submit" name="del" class="btn btn-danger" value="Cancelar" />
                </div>
            </form>
        </div>
    </div>
</div>
