<?php
$this->headScript()->prependFile($this->basePath() . '/js/ui-bootstrap-tpls-0.10.0.min.js');
$this->headScript()->prependFile($this->basePath() . '/js/angular.min.js');
?>  

<script>
    $(document).ready(function() {
        jQuery('#datahora').datetimepicker({
            format: 'd.m.Y H:i',
            allowTimes: ['08:00', '08:30', '09:00', '09:30', '10:00', '10:30', '11:00', '11:30',
                '12:00', '12:30', '13:00', '13:30', '14:00', '14:30', '15:00', '15:30',
                '16:00', '16:30', '17:00', '17:30'],
            inline: true,
            lang: 'pt'
        });
    });

    var app = angular.module('myApp', ['ui.bootstrap']);
    app.filter('startFrom', function() {
        return function(input, start) {
            if (input) {
                start = +start; //parse to int
                return input.slice(start);
            }
            return [];
        }
    });
    app.controller('customersCrtl', function($scope, $http, $timeout) {
        $http.get('<?php echo $this->url('ligacoes', array('action' => 'listaligacoes')); ?>').success(function(data) {
            $scope.list = data;
            $scope.currentPage = 1; //current page
            $scope.entryLimit = 10; //max no of items to display in a page
            $scope.filteredItems = $scope.list.length; //Initially for no filter  
            $scope.totalItems = $scope.list.length;
        });
        $scope.setPage = function(pageNo) {
            $scope.currentPage = pageNo;
        };
        $scope.filter = function() {
            $timeout(function() {
                $scope.filteredItems = $scope.filtered.length;
            }, 10);
        };
        $scope.sort_by = function(predicate) {
            $scope.predicate = predicate;
            $scope.reverse = !$scope.reverse;
        };
    });

</script>

<!-- Modal Notas -->
<div class="modal fade" id="ModalNotas" tabindex="-1" role="dialog" aria-labelledby="ModalNotasLabel" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                <h4 class="modal-title" id="myModalLabel">Registrando Anotações</h4>
            </div>
            <div class="modal-body">
                <div class='row'>
                    <div class="col-md-4">
                        <label class="control-label" for="status">Status</label>
                        <select name="form_projeto" id="projeto" class="form-control input-sm" required="required">
                            <option value="" selected="selected">Realizada</option>
                            <option value="" selected="selected">Remarcada</option>
                            <option value="" selected="selected">Adiada</option>
                            <option value="" selected="selected">Cancelada</option>
                        </select>
                        <span class="help-block">Status da Ligação <a class="flat-button-label" href="#" data-toggle="tooltip" data-placement="left" data-original-title="Para quem a ligação será realizada?"> <span class="glyphicon" data-icon=""></span></a></span>  
                    </div>
                    <div class="col-md-4">
                        <label class="control-label" for="duracao">Duração</label>
                        <input name="duracao" type="text" id="membro" class="form-control&#x20;input-sm" placeholder="Minutos ao Telefone" value="">
                        <span class="help-block">Caso aplicável <a class="flat-button-label" href="#" data-toggle="tooltip" data-placement="left" data-original-title="Caso a ligação tenha sido realizada, digite, em minutos, a duração desta ligação"> <span class="glyphicon" data-icon=""></span></a></span>  
                    </div>                                
                    <div class="col-md-4">
                        <label class="control-label clearfix" for="destinatario">&nbsp;</label>
                        <div class="checkbox">
                            <label><input type="checkbox"> Marcar na Agenda</label>
                        </div>
                        <span class="help-block">Marcar compromisso na Agenda <a class="flat-button-label" href="#" data-toggle="tooltip" data-placement="left" data-original-title="Para quem a ligação será realizada?"> <span class="glyphicon" data-icon=""></span></a></span>  
                    </div>
                </div>
                <div class='row'>
                    <div class="col-md-12">
                        <label class="control-label" for="assunto">Nota:</label>
                        <textarea name="form_DesAc" id="DesAc" class="form-control" cols="40" rows="8" required="required"></textarea>
                        <span class="help-block">Descreva a ligação <a class="flat-button-label" href="#" data-toggle="tooltip" data-placement="left" data-original-title="Qual assunto será tratado nesta ligação?"> <span class="glyphicon" data-icon=""></span></a></span>  
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary">Salvar</button>
            </div>
        </div>
    </div>
</div>

<div class="col-md-12">
    <legend class="clearfix">
        <span class="glyphicon" data-icon="a"></span> Ligações 
        <a class="btn-sm btn-primary" href="<?php echo $this->url('ligacoes', array('action' => 'add')); ?>" data-placement="left" data-original-title="Adicionar Contato"><span data-icon="&#xe03e;" class="glyphicon"></span> Adicionar</a> 
    </legend>
</div>

<div class="col-md-12"> 
    <div ng-controller="customersCrtl" style="margin-bottom: 75px;">
        <div>
            <div class="row">
                <div class="col-md-2">Registros por página:
                    <select ng-model="entryLimit" class="form-control">
                        <option>5</option>
                        <option>10</option>
                        <option>20</option>
                        <option>50</option>
                        <option>100</option>
                    </select>
                </div>
                <div class="col-md-3">Pesquisa:
                    <input type="text" ng-model="search" ng-change="filter()" placeholder="Pesquise um dos campos" class="form-control" />
                </div>
                <div class="col-md-4">
                    <h5>Exibindo {{ filtered.length}} de {{ totalItems}} contatos</h5>
                </div>
            </div>
            <br/>
            <div class="row">
                <div class="col-md-12" ng-show="filteredItems > 0">
                    <table class="table table-striped table-bordered">
                        <thead>
                        <th>ID&nbsp;<a ng-click="sort_by('id_ligacao');"><i class="glyphicon glyphicon-sort"></i></a></th>
                        <th>Membro&nbsp;<a ng-click="sort_by('membro');"><i class="glyphicon glyphicon-sort"></i></a></th>
                        <th>Destinatário&nbsp;<a ng-click="sort_by('destinatario');"><i class="glyphicon glyphicon-sort"></i></a></th>
                        <th>Assunto&nbsp;<a ng-click="sort_by('assunto');"><i class="glyphicon glyphicon-sort"></i></a></th>
                        <th>Data/Hora&nbsp;<a ng-click="sort_by('data_hora');"><i class="glyphicon glyphicon-sort"></i></a></th>
                        <th>Status&nbsp;<a ng-click="sort_by('status_ligacao');"><i class="glyphicon glyphicon-sort"></i></a></th>
                        <th></th>
                        </thead>
                        <tbody>
                            <tr ng-repeat="data in filtered = (list| filter:search | orderBy : predicate :reverse) | startFrom:(currentPage - 1) * entryLimit | limitTo:entryLimit">
                                <td>{{data.id_ligacao}}</td>
                                <td>{{data.membro}}</td>
                                <td>{{data.destinatario}}</td>
                                <td>{{data.assunto}}</td>
                                <td>{{data.data_hora}}</td>
                                <td ng-if="data.status_ligacao == 'Realizado'"><span class="badge badge-success">Realizado</span></td>
                                <td ng-if="data.status_ligacao == 'Pendente'"><span class="badge badge-warning">Pendente</span></td>
                                <td ng-if="data.status_ligacao == 'Remarcado'"><span class="badge badge-warning">Remarcado</span></td>
                                <td ng-if="data.status_ligacao == 'Cancelado'"><span class="badge badge-important">Cancelado</span></td>
                                <td class="text-right">
                                    <a href="<?php echo $this->url('ligacoes', array('action' => 'view', 'form_codigo')); ?>/{{data.id_ligacao}}" data-placement="left" data-original-title="Ver detalhes"><span class="glyphicon" data-icon="&#xe18e;"></span></a>
                                    <a href="<?php echo $this->url('ligacoes', array('action' => 'anotacoes', 'form_codigo')); ?>/{{data.id_ligacao}}" data-placement="left" data-original-title="Adicionar anotações"><span class="glyphicon" data-icon="&#xe04b;"></span></a>
                                    <a href="<?php echo $this->url('ligacoes', array('action' => 'edit', 'form_codigo')); ?>/{{data.id_ligacao}}" data-toggle="tooltip" data-placement="left" data-original-title="Editar"><span class="glyphicon" data-icon=""></span></a>
                                    <a href="<?php echo $this->url('ligacoes', array('action' => 'del', 'form_codigo')); ?>/{{data.id_ligacao}}" data-toggle="tooltip" data-placement="left" data-original-title="Cancelar"><span class="glyphicon" data-icon="&#xe1d6;"></span></a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="col-md-12" ng-show="filteredItems == 0">
                    <div class="col-md-12">
                        <h4>Nenhum Resultado para sua Pesquisa</h4>
                    </div>
                </div>
                <div class="col-md-12" ng-show="filteredItems > 0">    
                    <div pagination="" page="currentPage" on-select-page="setPage(page)" boundary-links="true" total-items="filteredItems" items-per-page="entryLimit" class="pagination-small" previous-text="&laquo;" next-text="&raquo;"></div>
                </div>
            </div>
        </div>
    </div>
</div>