<?php
$title = 'Excluir Contato';
$this->headTitle($title);
?>
<div class="container-fluid">
    <div class="table-responsive">
        <h1><?php echo $this->escapeHtml($title); ?></h1>

        <table class="table table-striped" id="datatable">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Órgão/Sigla</th>
                    <th>Cargo</th>
                </tr>
            </thead>
            <tbody>
                    <tr>
                        <td><?php echo $this->escapeHtml($contato->c_id); ?></td>
                        <td><?php echo $this->escapeHtml($contato->c_nome); ?></td>
                        <td><?php echo $this->escapeHtml($contato->c_sigla); ?></td>
                        <td><?php echo $this->escapeHtml($contato->c_cargo); ?></td>
                    </tr>
            </tbody>
        </table>
        <div class="col-md-12 text-center">
            <h2 class="sub-header" style="margin-bottom: 20px;">Confirma Exclusão?</h2>
        </div>
        <div class="col-md-12 text-center">
            <?php $url = $this->url('contatos', array('action' => 'del', 'form_codigo' => $this->form_codigo)); ?>
            <form action="<?php echo $url; ?>" method="post">
                <div>
                    <input type="hidden" name="form_codigo" value="<?php echo (int) $this->form_codigo; ?>" />
                    <input type="submit" name="del" class="btn btn-primary" value="Confirmar" />
                    <input type="submit" name="del" class="btn btn-danger" value="Cancelar" />
                </div>
            </form>
        </div>
    </div>
</div>
