<div class="container-fluid">
    <?php
    $this->headScript()->prependFile($this->basePath() . '/js/ui-bootstrap-tpls-0.10.0.min.js');
    $this->headScript()->prependFile($this->basePath() . '/js/angular.min.js');
    ?>     
    <script>
        var app = angular.module('myApp', ['ui.bootstrap']);
        app.filter('startFrom', function() {
            return function(input, start) {
                if (input) {
                    start = +start; //parse to int
                    return input.slice(start);
                }
                return [];
            }
        });
        app.controller('customersCrtl', function($scope, $http, $timeout) {
            $http.get('<?php echo $this->url('contatos', array('action' => 'listacontatos')); ?>').success(function(data) {
                $scope.list = data;
                $scope.currentPage = 1; //current page
                $scope.entryLimit = 10; //max no of items to display in a page
                $scope.filteredItems = $scope.list.length; //Initially for no filter  
                $scope.totalItems = $scope.list.length;
            });
            $scope.setPage = function(pageNo) {
                $scope.currentPage = pageNo;
            };
            $scope.filter = function() {
                $timeout(function() {
                    $scope.filteredItems = $scope.filtered.length;
                }, 10);
            };
            $scope.sort_by = function(predicate) {
                $scope.predicate = predicate;
                $scope.reverse = !$scope.reverse;
            };
        });
    </script>

    <?php if (isset($_SESSION['User']['userId'])) { ?>
        <nav>
            <div class="navbar-header pull-right">
                <a id="nav-expander" class="nav-expander fixed">
                    <span class="glyphicon" data-icon="&#xe0a5;"></span>
                </a>
            </div>
            <ul class="list-unstyled main-menu">
                <?php foreach ($this->users as $res) { ?>
                    <li class="clearfix"><span class="pull-left"><?php echo $res['nome'] . " " . $res['sobrenome']; ?></span> <span class="pull-right"><input type="checkbox" name="situacao-membro" id="<?php echo $res['id']; ?>" <?php if ($res['status'] == "Active") {
                echo "checked";
            } ?> data-size="small" data-on-text="Presente" data-off-text="Ausente" data-on-color="success" data-off-color="danger" data-label-text="< >"></span></li>
        <?php } ?>
            </ul>
        </nav>
<?php } ?>

    <div class="col-md-12">
        <legend class="clearfix">
            <span class="glyphicon" data-icon="a"></span> Contatos 
            <a class="btn-sm btn-primary" href="<?php echo $this->url('contatos', array('action' => 'add')); ?>" data-placement="left" data-original-title="Adicionar Contato"><span data-icon="&#xe03e;" class="glyphicon"></span> Adicionar</a> 
        </legend>

        <div ng-controller="customersCrtl">
            <div>
                <div class="row">
                    <div class="col-md-2">Registros por página:
                        <select ng-model="entryLimit" class="form-control">
                            <option>5</option>
                            <option>10</option>
                            <option>20</option>
                            <option>50</option>
                            <option>100</option>
                        </select>
                    </div>
                    <div class="col-md-3">Pesquisa:
                        <input type="text" ng-model="search" ng-change="filter()" placeholder="Pesquise um dos campos" class="form-control" />
                    </div>
                    <div class="col-md-4">
                        <h5>Exibindo {{ filtered.length}} de {{ totalItems}} contatos</h5>
                    </div>
                </div>
                <br/>
                <div class="row">
                    <div class="col-md-12" ng-show="filteredItems > 0">
                        <table class="table table-striped table-bordered">
                            <thead>
                            <th>ID&nbsp;<a ng-click="sort_by('id_contato');"><i class="glyphicon glyphicon-sort"></i></a></th>
                            <th>Nome&nbsp;<a ng-click="sort_by('nome_completo');"><i class="glyphicon glyphicon-sort"></i></a></th>
                            <th>Sigla&nbsp;<a ng-click="sort_by('o_sigla');"><i class="glyphicon glyphicon-sort"></i></a></th>
                            <th>Cargo&nbsp;<a ng-click="sort_by('cargo');"><i class="glyphicon glyphicon-sort"></i></a></th>
                            <th>Telefone/Ramal&nbsp;<a ng-click="sort_by('fone');"><i class="glyphicon glyphicon-sort"></i></a></th>
                            <th>Celular&nbsp;<a ng-click="sort_by('celular');"><i class="glyphicon glyphicon-sort"></i></a></th>
                            <th>Email&nbsp;<a ng-click="sort_by('email');"><i class="glyphicon glyphicon-sort"></i></a></th>
                            <th></th>
                            </thead>
                            <tbody>
                                <tr ng-repeat="data in filtered = (list| filter:search | orderBy : predicate :reverse) | startFrom:(currentPage - 1) * entryLimit | limitTo:entryLimit">
                                    <td>{{data.id_contato}}</td>
                                    <td>{{data.nome_completo}}</td>
                                    <td>{{data.o_sigla}}</td>
                                    <td>{{data.cargo}}</td>
                                    <td>{{data.fone}} / {{data.ramal}}</td>
                                    <td>{{data.celular}}</td>
                                    <td>{{data.email}}</td>
                                    <td>
                                        <a href="<?php echo $this->url('contatos', array('action' => 'edit', 'form_codigo')); ?>/{{data.id_contato}}" data-toggle="tooltip" data-placement="left" data-original-title="Editar"><span class="glyphicon" data-icon=""></span></a>
                                        <a href="<?php echo $this->url('contatos', array('action' => 'del', 'form_codigo')); ?>/{{data.id_contato}}" data-toggle="tooltip" data-placement="left" data-original-title="Excluir"><span class="glyphicon" data-icon="&#xe1d6;"></span></a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="col-md-12" ng-show="filteredItems == 0">
                        <div class="col-md-12">
                            <h4>Nenhum Resultado para sua Pesquisa</h4>
                        </div>
                    </div>
                    <div class="col-md-12" ng-show="filteredItems > 0">    
                        <div pagination="" page="currentPage" on-select-page="setPage(page)" boundary-links="true" total-items="filteredItems" items-per-page="entryLimit" class="pagination-small" previous-text="&laquo;" next-text="&raquo;"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>