<?php
$title = 'Excluir Usuário';
$this->headTitle($title);
?>
<div class="container-fluid">
    <div class="table-responsive">
        <h1><?php echo $this->escapeHtml($title); ?></h1>

        <table class="table table-striped" id="datatable">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome/Sobrenome</th>
                    <th>Email</th>
                    <th>Grupo/Função</th>
                    <th>Órgão(s)</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <?php
                    if ($users->u_status == "Active"){
                        $status = '<span class="badge badge-success">Ativo</span>';
                    }elseif ($users->u_status == "Inactive") {
                        $status = '<span class="badge badge-important">Inativo</span>';
                    }
                    //echo $_SESSION['User']['userOrgaos'];
                ?>
                <tr>
                    <td><?php echo $this->escapeHtml($users->u_id);?></td>
                    <td><?php echo $this->escapeHtml($users->u_first_name);?> <?php echo $this->escapeHtml($users->u_last_name);?></td>
                    <td><?php echo $this->escapeHtml($users->u_email);?></td>
                    <td><?php echo $this->escapeHtml($users->r_nome);?></td>
                    <td><?php echo $this->escapeHtml($users->u_orgaos);?></td>
                    <td><?php echo $status; ?></td>
                </tr>
            </tbody>
        </table>
        <div class="col-md-12 text-center">
            <h2 class="sub-header" style="margin-bottom: 20px;">Confirma Exclusão?</h2>
        </div>
        <div class="col-md-12 text-center">
            <?php $url = $this->url('users', array('action' => 'user-del', 'form_users' => $this->form_id)); ?>
            <form action="<?php echo $url; ?>" method="post">
                <div>
                    <input type="hidden" name="u_id" value="<?php echo (int) $this->form_id; ?>" />
                    <input type="submit" name="del" class="btn btn-primary" value="Confirmar" />
                    <input type="submit" name="del" class="btn btn-danger" value="Cancelar" />
                </div>
            </form>
        </div>
    </div>
</div>
