<?php
$this->headLink()->prependStylesheet($this->basePath() . '/css/jquery.datetimepicker.css');
$this->headScript()->prependFile($this->basePath() . '/js/jquery.datetimepicker.js');
echo $this->headScript()
        ->prependFile($this->basePath() . '/js/jqueryui-multisearch.js')
        ->prependFile($this->basePath() . '/js/lodash.underscore.min.js')
        ->prependFile($this->basePath() . '/js/jquery-ui.js');
?>  
<style>
    textarea {
        resize: none;
        font-size: 12px !important;
    }

    input[data-role="input"] {
        outline: none;
        border: none;
        font-size: 12px;
        color: #555;
        vertical-align: middle;
        padding: 3px 4px;
        margin: 3px;
    }

    input.error {
        color: #f00;
    }

    [data-role="picker"] {
        z-index: 1080;
    }

    a:focus {
        outline: none;
    }

    a.list-group-item.hover {
        background-color: #F5F5F5;
        text-decoration: none;
    }

    a.label-default {
        cursor: pointer;
        font-size: 12px;
        margin: 3px;
        color: #555;
        background-color: #F7F7F7;
        text-decoration: none;
    }

    a.label-default.hover {
        background-color: #DFDFDF;
        text-decoration: none;
    }

    a.label-default.active {
        text-decoration: none;
    }

    .panel {
        margin: 0;
        transition: border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s;
    }

    .panel.focus {
        border-color: #66AFE9;
        box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset, 0 0 8px rgba(102, 175, 233, 0.6);
        outline: 0 none;
    }

    .panel-body {
        padding: 3px 6px;
    }

    .popover {
        max-width: 347px;
        min-width: 276px;
    }

    .popover-content {
        overflow: hidden;
        font-size: 90%;
    }

    .popover-content .col-lg-4, .popover-content .col-lg-8 {
        padding: 0 5px
    }
</style>
<script id="multisearch" type="text/template">
    <div>
    <div class="panel panel-default">
    <div data-role="selected-list" class="panel-body">
    <input class="pull-left" data-role="input" type="text" placeholder=""/>
    </div>
    </div>
    <div data-role="picker" class="panel panel-default">
    <div class="list-group" data-role="picker-list">
    </div>
    </div>
    </div>
</script>

<script id="contact-item" type="text/template">
    <a class="list-group-item" href="#">
    <small><%= nome_contato %> (<%= end_email %>)</small>
    </a>
</script>

<script id="selected-item" type="text/template">
    <a class="label label-default pull-left"><%= nome_contato %>&nbsp;<span class="glyphicon glyphicon-remove" data-action="remove" aria-hidden="true"></span></a>
</script>

<script id="contact-info" type="text/template">
    <div class="popover bottom fade">
    <div class="arrow"></div>
    <h3 class="popover-title"><b><%= nome_contato %></b></h3>
    <div class="popover-content">

    <div class="row">
    <div class="col-lg-4 text-right"><strong>Órgão</strong></div>
    <div class="col-lg-8"><%= sigla_orgao %></div>
    </div>

    <div class="row">
    <div class="col-lg-4 text-right"><strong>Email</strong></div>
    <div class="col-lg-8"><%= end_email %> (<%= tipo_email %>)</div>
    </div>

    <div class="row">
    <div class="col-lg-4 text-right"><strong>Cargo</strong></div>
    <div class="col-lg-8"><%= cargo_contato %></div>
    </div>

    </div>
    </div>
</script>
<script>
    $(document).ready(function () {
        auto_complete();
        jQuery('#datahora').datetimepicker({
            format: 'Y-m-d H:i:s',
            inline: true,
            lang: 'pt'
        });
    });
    
    function auto_complete() {
        var multiSearch = _.template($('#multisearch').html()),
                infoBox = _.template($('#contact-info').html());

        // Since you can tab through fields, redirect the focus
        // event to click just in case.
        $(document.body).on('focusin', 'input, textarea', function (event) {
            $(event.target).trigger('click');


        });

        $('div[data-control="multisearch"]').append(multiSearch())
                .children()

                .on('click', function simulateFocus(event) {
                    var $me = $(this),
                            $panel = $me.find('.panel');
                    if (!$panel.is('.focus')) {

                        $panel.addClass('focus');

                        _.defer(function () {
                            $(document.body).on('click.focus', function (e) {
                                if ($me.has(e.target).length === 0) {
                                    $panel.removeClass('focus');
                                    $(document.body).off('click.focus');
                                }
                            });
                        });
                    }

                })

                .multisearch({
                    source: localData,
                    keyAttrs: ['id_email'],
                    searchAttrs: ['nome_contato', 'end_email', 'sigla_orgao'],
                    formatPickerItem: _.template($('#contact-item').html()),
                    formatSelectedItem: _.template($('#selected-item').html()),
                    buildNewItem: function (text) {
                        return {id_email: text, nome_contato: text, sigla_orgao: text, primary_email: text, tipo_email: text};
                    },
                    
                    adding: function (event, ui) {
                        var validater = new RegExp('^(?:[^,]+@[^,/]+\.[^,/]+|)$');
                        var TxtInput = $("#origem");
                        $(TxtInput).val(TxtInput.val()+ui.data.id_email);
                        $(this).find('input').removeClass('error');
                        if (ui.notfound) {
                            if (!validater.test(ui.data.id_email)) {
                                $(this).find('input').addClass('error');
                                return false;
                            }
                        }
                    },
                    
                    itemselect: function (event, ui) {
                        // Generate from template and add to DOM
                        var $info = $(infoBox(ui.data)).insertAfter($(this)).show();

                        // Use jQueryUI Position utility to move it to the right spot
                        $info.position({
                            my: 'center top+10',
                            at: 'center bottom',
                            of: ui.element
                        });

                        $info.addClass('in');
                        _.defer(function () {
                            $(document).on('click.info', function (e) {
                                if ($info.has(e.target).length === 0) {
                                    $info.removeClass('in');
                                    _.delay(function () {
                                        $info.remove();
                                    }, 500);
                                    $(document).off('click.info');
                                }
                            });

                        });
                    },
                });
    }
</script>
<script>
    localData = <?php echo json_encode($this->contatos); ?>;
    // Need an id ... auto-generate it
    for (var i = 1; i < localData.length; i++)
        localData[i].id = i;
</script>
<?php
$title = 'Agendando Comunicação';
$this->headTitle($title);
?>
<div class="container-fluid">
    <div class="table-responsive">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('comunicacoes', array('action' => 'add')));
        $form->prepare();
        echo $this->form()->openTag($form) . PHP_EOL;
        ?>
        <legend><?php echo $this->escapeHtml($title); ?></legend>
        <?php echo $this->formHidden($form->get('form_codigo')) . PHP_EOL; ?>
        <?php if ($this->mensagem) { ?>
            <div style="margin-top:10px;"><div class="alert alert-success">Comunicação agendada com sucesso! <a class="btn btn-success" href="<?php echo $this->url('comunicacoes'); ?>" data-original-title="" title=""><span data-icon="" class="glyphicon"></span> Retornar para Comunicações</a></div></div>
        <?php } ?>

        <div class='row'>
            <div class="col-md-2">
                <label class="control-label" for="form_status">Status</label>
                <?php echo $this->formRow($form->get('form_status')) . PHP_EOL; ?>
                <span class="help-block">Status deste Contato <a class="flat-button-label" href="#" data-toggle="tooltip" data-placement="bottom" data-original-title="Digite ou selecione um membro"> <span class="glyphicon" data-icon=""></span></a></span>  
            </div>
            <div class="col-md-2">
                <label class="control-label" for="form_tipo">Tipo</label>
                <?php echo $this->formRow($form->get('form_tipo')) . PHP_EOL; ?>
                <span class="help-block">Tipo de Comunicação <a class="flat-button-label" href="#" data-toggle="tooltip" data-placement="bottom" data-original-title="Digite ou selecione um membro"> <span class="glyphicon" data-icon=""></span></a></span>  
            </div>
            <div class="col-md-4">
                <label class="control-label" for="form_projeto">Projeto</label>
                <?php echo $this->formRow($form->get('form_projeto')) . PHP_EOL; ?>
                <span class="help-block">Selecione um Projeto caso esteja envolvido <a class="flat-button-label" href="#" data-toggle="tooltip" data-placement="bottom" data-original-title="Digite ou selecione um membro"> <span class="glyphicon" data-icon=""></span></a></span>  
            </div>
            <div class="col-md-4">
                <label class="control-label" for="form_etapas">Etapa</label>
                <?php echo $this->formRow($form->get('form_etapas')) . PHP_EOL; ?>
                <span class="help-block">Selecione uma Etapa caso esteja envolvida <a class="flat-button-label" href="#" data-toggle="tooltip" data-placement="bottom" data-original-title="Digite ou selecione um membro"> <span class="glyphicon" data-icon=""></span></a></span>  
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <label class="control-label" for="form_origem">Remetente</label>
                <?php //echo $this->formRow($form->get('form_origem')) . PHP_EOL; ?>
                <div data-control="multisearch" size="32" class="form_origem"></div>
                <input type="text" name="origem" id="origem"/>
                <span class="help-block">Digite ou selecione um membro <a class="flat-button-label" href="#" data-toggle="tooltip" data-placement="bottom" data-original-title="Digite ou selecione um membro"> <span class="glyphicon" data-icon=""></span></a></span>  
            </div>
            <div class="col-md-6">
                <label class="control-label" for="form_destino">Destinatário</label>
                <?php //echo $this->formRow($form->get('form_destino')) . PHP_EOL; ?>
                <div data-control="multisearch" size="32" class="destino"></div>
                <input type="text" name="destino" id="destino"/>
                <span class="help-block">Digite ou selecione um destinatário <a class="flat-button-label" href="#" data-toggle="tooltip" data-placement="bottom" data-original-title="Para quem a ligação será realizada?"> <span class="glyphicon" data-icon=""></span></a></span>  
            </div>
        </div>
        <div class='row'>
            <div class="col-md-9">
                <label class="control-label" for="form_assunto">Assunto</label>
                <?php echo $this->formRow($form->get('form_assunto')) . PHP_EOL; ?>
                <span class="help-block">Assunto deste contato <a class="flat-button-label" href="#" data-toggle="tooltip" data-placement="bottom" data-original-title="Qual assunto será tratado nesta ligação?"> <span class="glyphicon" data-icon=""></span></a></span>  
            </div>
            <div class="col-md-3">
                <label class="control-label" for="form_data">Data/Horário</label>
                <?php echo $this->formRow($form->get('form_data')) . PHP_EOL; ?>
                <span class="help-block">Selecione a Data/Hora <a class="flat-button-label" href="#" data-toggle="tooltip" data-placement="bottom" data-original-title="Selecione a Data/Hora que esta ligação deverá ser realizada"> <span class="glyphicon" data-icon=""></span></a></span>  
            </div>
        </div>

        <div class="col-md-12">
            <button class="btn btn-primary" name="adicionar" id="adicionar"><span data-icon="" class="glyphicon"></span> Agendar</button>
        </div>
        <?php echo $this->form()->closeTag($form) . PHP_EOL; ?>
    </div>
</div>

<script type="text/javascript">
    $('#form_projeto').change(function() {
        var proj_id = $('#form_projeto').val();
        if (proj_id === '') {
            $('#form_etapas').html('<option value="empty_option">:: Primeiro selecione um Projeto ::</option>');
        } else {
            get_etapas(proj_id);
        }
    });
    
    function get_etapas(proj_id) {
        var projeto = $('#form_projeto').val();
        $.ajax('<?php echo $this->url('comunicacoes', array('action' => 'get-etapas')); ?>?proj_id='+ projeto, {
            type: 'get',
            dataType: 'json',
            data: {
                proj_id: proj_id
            },
            success: function(data) {
                $('#form_etapas').html('');
                $.each(data, function(index, etapas) {
                    $('#form_etapas').append('<option value="' + etapas.valor + '">' + etapas.label + '</option>');
                });
            },
            error: function(error) {
            }
        });
    }
</script>