<?php
$this->headScript()->prependFile($this->basePath() . '/js/ui-bootstrap-tpls-0.10.0.min.js');
$this->headScript()->prependFile($this->basePath() . '/js/angular.min.js');
?>  

<?php
$title = 'Detalhes da Ligação "' . $this->escapeHtml($comunicacao->id_comunicacao) . '"';
$this->headTitle($title);
$date = new \DateTime($this->escapeHtml($comunicacao->data));
$dataAtual = $date->format('d/m/Y à\s H:i');
?>

<div class="container-fluid">

    <div class="table-responsive">
        <h1><?php echo $this->escapeHtml($title); ?></h1>

        <table class="table table-striped">
            <tr>
                <th><strong>De:</strong></th>
                <td>
                        <?php 
                        foreach ($this->remetentes as $res) {
                            if(count($this->remetentes) > 1){
                                echo "<i>".$res['nomecontatos']."</i>, ";
                            }else{
                                echo "<i>".$res['nomecontatos']."</i>";
                            }
                        }
                        ?>
                </td>
            </tr>
            <tr>
                <th><strong>Para:</strong></th>
                <td>
                        <?php 
                        foreach ($this->destinatarios as $res) {
                            if(count($this->destinatarios) > 1){
                                echo "<i>".$res['nomecontatos']."</i>, ";
                            }else{
                                echo "<i>".$res['nomecontatos']."</i>";
                            }
                        }
                        ?>
                </td>
            </tr>
            <tr>
                <th><strong>Assunto:</strong></th>
                <td><i><?php echo $this->escapeHtml($comunicacao->descricao); ?></i></td>
            </tr>
            <tr>
                <th><strong>Horário:</strong></th>
                <td><i><?php echo $dataAtual; ?></i></td>
            </tr>
            <tr>
                <th><strong>Status:</strong></th>
                <td><i><?php echo $this->escapeHtml($comunicacao->status); ?></i></td>
            </tr>
        </table>
        <div ng-controller="fessCntrl">
            <table class="table table-striped">
                <tr>
                    <th colspan="2"><strong>Notas:</strong></th>
                </tr>
                <?php foreach ($this->log as $res) { 
                    $date_log = new \DateTime($this->escapeHtml($res['data_log']));
                    $data_log = $date_log->format('d/m/Y à\s H:i');
                    ?>
                    <tr>
                        <td colspan="2"><?php echo $data_log; ?> - <?php echo $res['nota']; ?></td>
                    </tr>
                <?php } ?>
            </table>
        </div>
    </div>
</div>
</div>
